### ISSUE TITLE
Ant Design Vue 本地预览项目正常。 编译打包后不加载二级菜单页面内容，不显示页面主要内容，请问是什么原因啊？

### ISSUE THREAD

**Issue by ymw2017** [sendya/ant-design-pro-vue#1197]
Ant Design Vue 本地预览项目正常。 编译打包后不加载二级菜单页面内容，不显示页面主要内容，请问是什么原因啊？

**Comment by sendya** [comment]
提供复现仓库 谢谢

**Comment by hooyoa** [comment]
我也出现了，好像 npm 安装的依赖的问题，今天更新了一下依赖出现你描述的问题。后来用旧的 node_modules 覆盖，正常（以前出现过，所以隔段时间会备份下 node_modules），赶进度，等有空找到具体哪个包引起，再留言

**Comment by watsonhaw5566** [comment]
> 我也出现了，好像 npm 安装的依赖的问题，今天更新了一下依赖出现你描述的问题。后来用旧的 node_modules 覆盖，正常（以前出现过，所以隔段时间会备份下 node_modules），赶进度，等有空找到具体哪个包引起，再留言

我这边最近也是这个问题，感觉是有些包更新了。目前用yarn.lock暂时解决问题。

**Comment by hooyoa** [comment]
后面 vue.config.js，以下几个cdn地址改成 node_modules 对应本部号，正常
    '//cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js',
    '//cdn.jsdelivr.net/npm/vue-router@3.5.2/dist/vue-router.min.js',
    '//cdn.jsdelivr.net/npm/vuex@3.6.2/dist/vuex.min.js',
    '//cdn.jsdelivr.net/npm/axios@0.19.2/dist/axios.min.js'

**Comment by watsonhaw5566** [comment]
> 后面 vue.config.js，以下几个cdn地址改成 node_modules 对应本部号，正常
> '//cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js',
> '//cdn.jsdelivr.net/npm/vue-router@3.5.2/dist/vue-router.min.js',
> '//cdn.jsdelivr.net/npm/vuex@3.6.2/dist/vuex.min.js',
> '//cdn.jsdelivr.net/npm/axios@0.19.2/dist/axios.min.js'

也可以把vue.config.js把 Vue生产cdn注释掉，这样就会使用node_modules里的Vue。
![image](https://user-images.githubusercontent.com/4210367/125242407-3a81ab80-e31f-11eb-8ee2-8f4a2ccb7fa2.png)

**Comment by dongpobaicai** [comment]
果然是cdn版本，和node_modules版本问题

**Comment by LeBron-labc** [comment]
就是 cdn版本问题, 我的改完也好了 ,  感谢!!
