### ISSUE TITLE
文档连接失效

### ISSUE THREAD

**Issue by dgsfor** [sendya/ant-design-pro-vue#1262]
https://pro.antdv.com/docs/new-page#%E4%BA%8C%E3%80%81%E5%B0%86%E6%96%87%E4%BB%B6%E5%8A%A0%E5%85%A5%E8%8F%9C%E5%8D%95%E5%92%8C%E8%B7%AF%E7%94%B1

这个页面的` 路由和菜单 - 添加路由/菜单`超链接失效了

**Comment by sendya** [comment]
fixed
