### ISSUE TITLE
如何将原本的前端路由改为后端路由，要改哪些地方？

### ISSUE THREAD

**Issue by lipeng22** [sendya/ant-design-pro-vue#733]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/store/index.js#L10-L12

具体自行跟踪，也可以看看 pro 的文档（权限）部分
